spring.application.name=pulseops-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/pulseops
spring.datasource.username=harrybrar
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
